# Generated by Django 2.1.7 on 2021-12-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_question_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isTrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('PL', 'Poll'), ('QZ', 'Quizz'), ('WC', 'Word Cloud')], default='PL', max_length=2, verbose_name='Type of Question'),
        ),
    ]
