# Generated by Django 2.1.7 on 2021-12-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20211224_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Question')),
                ('desc', models.TextField(max_length=200, verbose_name='Description')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('featured', models.BooleanField(verbose_name='Feature in Featured Polls Page')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public in polls page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poll.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll')),
            ],
            bases=('poll.choice',),
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Question')),
                ('desc', models.TextField(max_length=200, verbose_name='Description')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('featured', models.BooleanField(verbose_name='Feature in Featured Polls Page')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public in polls page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizzChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poll.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Quizz')),
            ],
            bases=('poll.choice',),
        ),
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Question')),
                ('desc', models.TextField(max_length=200, verbose_name='Description')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('featured', models.BooleanField(verbose_name='Feature in Featured Polls Page')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public in polls page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordCloudChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poll.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.WordCloud')),
            ],
            bases=('poll.choice',),
        ),
    ]
