# Generated by Django 2.1.7 on 2021-12-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20211224_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Question')),
                ('desc', models.TextField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.Meeting'),
            preserve_default=False,
        ),
    ]
