# Generated by Django 4.0 on 2022-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_choice_id_alter_meeting_id_alter_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=50, verbose_name='Your Name')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='code',
            field=models.CharField(default='P1F02021', max_length=50, verbose_name='Security Code for joining the Meeting'),
        ),
    ]
