# Generated by Django 4.0 on 2022-01-06 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_attendee_meeting_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of start'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date_stop',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of end'),
        ),
    ]
