# Generated by Django 4.0 on 2022-01-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_remove_meeting_meeting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date_start',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date_stop',
        ),
        migrations.AddField(
            model_name='meeting',
            name='has_started',
            field=models.BooleanField(default=False, verbose_name='Meeting has started'),
        ),
    ]
