# Generated by Django 4.0 on 2022-01-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_remove_meeting_meeting_date_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
