# Generated by Django 4.0 on 2022-01-06 17:38

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_order']},
        ),
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='meeting',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.meeting'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to=None,
        ),
    ]
