# Generated by Django 4.0 on 2022-01-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_remove_question_featured_remove_question_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Question already completed'),
        ),
    ]
