# Generated by Django 4.0 on 2022-01-11 09:58

from django.db import migrations, models
import django.utils.timezone
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_alter_question_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='desc_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='desc',
            field=markdownfield.models.MarkdownField(max_length=200, rendered_field='desc_rendered', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('PL', 'Poll'), ('TX', 'Text Only'), ('QZ', 'Quizz'), ('WC', 'Word Cloud')], default='PL', max_length=2, verbose_name='Type of Question'),
        ),
    ]
