# Generated by Django 4.0 on 2022-01-11 10:06

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_alter_meeting_desc_rendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desc_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=markdownfield.models.MarkdownField(max_length=200, rendered_field='desc_rendered', verbose_name='Description'),
        ),
    ]
