# Generated by Django 4.0 on 2022-01-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_question_desc_rendered_alter_question_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='poll.meeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
