# Generated by Django 4.0 on 2022-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_attendee_meeting_attendee_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='reward_fastest',
            field=models.BooleanField(default=False, verbose_name='Reward the fastest answers'),
        ),
    ]
