# Generated by Django 4.0 on 2022-01-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0020_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
