# Generated by Django 4.0 on 2022-01-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_remove_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first_correct_answer',
            field=models.BooleanField(default=True, verbose_name='True if no one gave the correct answer already'),
        ),
    ]
