# Generated by Django 4.0 on 2022-01-12 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0023_meeting_date_meeting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of meeting'),
        ),
    ]
