# Generated by Django 4.0 on 2022-01-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0027_remove_meeting_date_meeting_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 18, 1, 41, 399341), verbose_name='End date and time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 16, 1, 41, 399295), verbose_name='Start date and time of the meeting'),
        ),
    ]
