# Generated by Django 4.0 on 2022-01-12 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0028_alter_meeting_date_end_alter_meeting_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 12, 32, 54, 107731, tzinfo=utc), verbose_name='End date and time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 10, 32, 54, 107558, tzinfo=utc), verbose_name='Start date and time of the meeting'),
        ),
    ]
