# Generated by Django 4.0 on 2022-01-12 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0029_alter_meeting_date_end_alter_meeting_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 12, 37, 42, 315327, tzinfo=utc), verbose_name='End date and time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date and time of the meeting'),
        ),
    ]
